# Generated by Django 3.2 on 2023-04-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genretitle',
            name='genre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre', to='reviews.genre', unique=True, verbose_name='Жанр(ы)'),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='title_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title', to='reviews.title', unique=True),
        ),
    ]
