# Generated by Django 3.2 on 2023-04-27 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230426_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genretitle',
            name='title_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='reviews.title'),
        ),
    ]
