# Generated by Django 3.2 on 2023-04-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20230427_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genretitle',
            name='title_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reviews.title', verbose_name='Произведение'),
        ),
    ]
