# Generated by Django 3.2 on 2023-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_genretitle_title_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(help_text='Название произведения не должно быть длиннее 256 символов', max_length=256, verbose_name='Название произведения'),
        ),
    ]
