# Generated by Django 3.2 on 2023-04-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_title_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(null=True, to='reviews.Genre', verbose_name='Жанр(ы) произведения'),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='genre_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reviews.genre', verbose_name='Жанр(ы)'),
        ),
    ]
