# Generated by Django 3.2 on 2023-04-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20230429_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['slug'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='title',
            name='descriptions',
            field=models.TextField(default=1, verbose_name='Описание произведения'),
            preserve_default=False,
        ),
    ]
