# Generated by Django 3.2 on 2023-04-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_category_nameoftitle'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='nameoftitle',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Название категории не должно быть длиннее 50 символов', max_length=50, unique=True, verbose_name='Название категории'),
        ),
    ]
