# Generated by Django 3.2 on 2023-04-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20230429_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание произведения'),
            preserve_default=False,
        ),
    ]
