# Generated by Django 3.2 on 2023-04-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['slug'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['slug'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['year'], 'verbose_name': 'Произведение'},
        ),
    ]
