# Generated by Django 3.2 on 2023-05-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_alter_title_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_title', to='reviews.category', verbose_name='Категория произведения'),
        ),
    ]
